apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.deploy.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.deploy.image.repository }}:{{ .Values.deploy.image.tag }}
        name: techtrends
        imagePullPolicy: {{. Values.deploy.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deploy.containerPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.deploy.livenessProbePath }}
            port: {{ .Values.deploy.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deploy.readinessProbePath }}
            port: {{ .Values.deploy.containerPort }}
        resources:
          requests:
            memory: {{ .Values.deploy.resources.requests.memory }}
            cpu: {{ .Values.deploy.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deploy.resources.limits.memory }}
            cpu: {{ .Values.deploy.resources.limits.cpu }}