apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace.name}}
  name: {{ .Values.namespace.name}}
  resourceVersion: "1217"
spec:
  finalizers:
  - kubernetes
status:
  phase: Active