namespace:
  name : sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

deploy:
  image:
    repository: riteshkhatri42/techtrends
    tags: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
  containerPort: 3111
  livenessProbePath: /healthz
  readinessProbePath: /healthz
  
  