namespace:
  name : staging

service:
  port: 5111
  # This will come from default values.yaml file
  # targetPort: 3111
  # protocol: TCP
  # type: ClusterIP

deploy:
  image:
    # repository: riteshkhatri42/techtrends
    # tags: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  resources:
    requests:
      memory: 90Mi
      cpu: 300m
    limits:
      memory: 128Mi
      cpu: 500m
  # containerPort: 3111
  # livenessProbePath: /healthz
  # readinessProbePath: /healthz
  
  